version: "3.8"
services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: smart_health
    ports: ["5432:5432"]
    volumes:
      - pgdata:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    ports: ["5672:5672","15672:15672"]
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  app:
    build: .
    depends_on:
      - postgres
      - rabbitmq
    environment:
      DATABASE_URL: "postgresql+asyncpg://postgres:postgres@postgres:5432/smart_health"
      RABBITMQ_URL: "amqp://guest:guest@rabbitmq/"
      API_KEY: "secret-key"
    ports: ["8000:8000"]
    volumes:
      - .:/app
volumes:
  pgdata:
